import type { ApiErrorDto } from '@/shared/types/api/envelope'

export class ApiError extends Error {
  readonly code: string
  readonly status: number
  readonly details: Record<string, unknown> | null

  constructor(error: ApiErrorDto, status: number) {
    super(error.message)
    this.name = 'ApiError'
    this.code = error.code
    this.status = status
    this.details = error.details
  }
}

export const ERROR_CODES = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  MEETING_NOT_FOUND: 'MEETING_NOT_FOUND',
  MEETING_ALREADY_ENDED: 'MEETING_ALREADY_ENDED',
  MEETING_NOT_PROCESSING: 'MEETING_NOT_PROCESSING',
  AUDIO_UPLOAD_FAILED: 'AUDIO_UPLOAD_FAILED',
  AUDIO_FORMAT_UNSUPPORTED: 'AUDIO_FORMAT_UNSUPPORTED',
  TRANSCRIPTION_FAILED: 'TRANSCRIPTION_FAILED',
  EXTRACTION_FAILED: 'EXTRACTION_FAILED',
  EXTRACTION_NOT_FOUND: 'EXTRACTION_NOT_FOUND',
  APPROVAL_NOT_FOUND: 'APPROVAL_NOT_FOUND',
  APPROVAL_ALREADY_RESOLVED: 'APPROVAL_ALREADY_RESOLVED',
  NOTION_WRITE_FAILED: 'NOTION_WRITE_FAILED',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  WORKSPACE_MISMATCH: 'WORKSPACE_MISMATCH',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  MEMBER_ALIAS_NOT_FOUND: 'MEMBER_ALIAS_NOT_FOUND',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_HISTORY_NOT_FOUND: 'TASK_HISTORY_NOT_FOUND',
  TASK_HISTORY_ALREADY_ROLLED_BACK: 'TASK_HISTORY_ALREADY_ROLLED_BACK',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  WORKSPACE_NAME_DUPLICATED: 'WORKSPACE_NAME_DUPLICATED',
  ONBOARDING_INCOMPLETE: 'ONBOARDING_INCOMPLETE',
  INTEGRATION_NOT_CONNECTED: 'INTEGRATION_NOT_CONNECTED',
  INTEGRATION_REVOKED: 'INTEGRATION_REVOKED',
  MEETING_PROCESSING_IN_PROGRESS: 'MEETING_PROCESSING_IN_PROGRESS',
  AUDIO_TOO_LARGE: 'AUDIO_TOO_LARGE',
  DISCORD_USER_ALREADY_MAPPED: 'DISCORD_USER_ALREADY_MAPPED',
} as const
