"""add_approval_request_and_update_change_source

Revision ID: 051b67bf8358
Revises: 3e053abba6cf
Create Date: 2026-09-12 00:05:48.456094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '051b67bf8358'
down_revision: Union[str, Sequence[str], None] = '3e053abba6cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_request',
    sa.Column('approval_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('related_task_id', sa.String(length=36), nullable=True),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['related_task_id'], ['task.task_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['member.member_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['member.member_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_index(op.f('ix_approval_request_related_task_id'), 'approval_request', ['related_task_id'], unique=False)
    op.create_index(op.f('ix_approval_request_status'), 'approval_request', ['status'], unique=False)
    op.create_index(op.f('ix_approval_request_workspace_id'), 'approval_request', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_request_workspace_id'), table_name='approval_request')
    op.drop_index(op.f('ix_approval_request_status'), table_name='approval_request')
    op.drop_index(op.f('ix_approval_request_related_task_id'), table_name='approval_request')
    op.drop_table('approval_request')
    # ### end Alembic commands ###
