"""initial schema

Revision ID: 3e053abba6cf
Revises: 
Create Date: 2026-09-09 16:16:05.889907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e053abba6cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting',
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('audio_merged', sa.Boolean(), nullable=False),
    sa.Column('transcribed', sa.Boolean(), nullable=False),
    sa.Column('extracted', sa.Boolean(), nullable=False),
    sa.Column('failed_stage', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('meeting_id')
    )
    op.create_index(op.f('ix_meeting_status'), 'meeting', ['status'], unique=False)
    op.create_index(op.f('ix_meeting_workspace_id'), 'meeting', ['workspace_id'], unique=False)
    op.create_table('member',
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('discord_user_id', sa.String(length=64), nullable=False),
    sa.Column('notion_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_index(op.f('ix_member_discord_user_id'), 'member', ['discord_user_id'], unique=True)
    op.create_index(op.f('ix_member_notion_name'), 'member', ['notion_name'], unique=False)
    op.create_index(op.f('ix_member_workspace_id'), 'member', ['workspace_id'], unique=False)
    op.create_table('alias_resolution_log',
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('alias_text', sa.String(length=100), nullable=False),
    sa.Column('resolved_member', sa.String(length=36), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('meeting_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resolved_member'], ['member.member_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_alias_resolution_log_alias_text'), 'alias_resolution_log', ['alias_text'], unique=False)
    op.create_index(op.f('ix_alias_resolution_log_workspace_id'), 'alias_resolution_log', ['workspace_id'], unique=False)
    op.create_table('audio_segment',
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=True),
    sa.Column('discord_user_id', sa.String(length=64), nullable=True),
    sa.Column('merged_start_ms', sa.Integer(), nullable=False),
    sa.Column('merged_end_ms', sa.Integer(), nullable=False),
    sa.Column('actual_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('track_file_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.meeting_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('segment_id')
    )
    op.create_index(op.f('ix_audio_segment_meeting_id'), 'audio_segment', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_audio_segment_merged_start_ms'), 'audio_segment', ['merged_start_ms'], unique=False)
    op.create_table('extraction',
    sa.Column('extraction_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('transcript_path', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.meeting_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('extraction_id')
    )
    op.create_index(op.f('ix_extraction_meeting_id'), 'extraction', ['meeting_id'], unique=False)
    op.create_table('meeting_audio',
    sa.Column('audio_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('merged_file_path', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('track_count', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.meeting_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audio_id'),
    sa.UniqueConstraint('meeting_id')
    )
    op.create_table('member_alias',
    sa.Column('alias_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('alias_text', sa.String(length=100), nullable=False),
    sa.Column('alias_type', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alias_id'),
    sa.UniqueConstraint('workspace_id', 'member_id', 'alias_text', name='uq_alias_per_member')
    )
    op.create_index(op.f('ix_member_alias_alias_text'), 'member_alias', ['alias_text'], unique=False)
    op.create_index(op.f('ix_member_alias_member_id'), 'member_alias', ['member_id'], unique=False)
    op.create_index(op.f('ix_member_alias_workspace_id'), 'member_alias', ['workspace_id'], unique=False)
    op.create_table('task',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('assignee_member_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('blocker', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notion_page_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_member_id'], ['member.member_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.meeting_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_task_assignee_member_id'), 'task', ['assignee_member_id'], unique=False)
    op.create_index(op.f('ix_task_due_date'), 'task', ['due_date'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('ix_task_workspace_id'), 'task', ['workspace_id'], unique=False)
    op.create_table('alias_review',
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('corrected_member', sa.String(length=36), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corrected_member'], ['member.member_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['log_id'], ['alias_resolution_log.log_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['member.member_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_alias_review_log_id'), 'alias_review', ['log_id'], unique=False)
    op.create_table('extraction_item',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('extraction_id', sa.String(length=36), nullable=False),
    sa.Column('task_title', sa.String(length=300), nullable=False),
    sa.Column('task_confidence', sa.Float(), nullable=False),
    sa.Column('assignee_raw', sa.String(length=100), nullable=True),
    sa.Column('assignee_member_id', sa.String(length=36), nullable=True),
    sa.Column('assignee_confidence', sa.Float(), nullable=False),
    sa.Column('assignee_needs_check', sa.Boolean(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_raw', sa.String(length=100), nullable=True),
    sa.Column('due_confidence', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('gate', sa.String(length=10), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('evidence_speaker', sa.String(length=100), nullable=True),
    sa.Column('evidence_at_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_member_id'], ['member.member_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['extraction_id'], ['extraction.extraction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_extraction_item_extraction_id'), 'extraction_item', ['extraction_id'], unique=False)
    op.create_table('task_history',
    sa.Column('history_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('changed_field', sa.String(length=20), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('change_source', sa.String(length=16), nullable=False),
    sa.Column('changed_by', sa.String(length=36), nullable=True),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('is_rolled_back', sa.Boolean(), nullable=False),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['member.member_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_task_history_is_auto'), 'task_history', ['is_auto'], unique=False)
    op.create_index(op.f('ix_task_history_is_rolled_back'), 'task_history', ['is_rolled_back'], unique=False)
    op.create_index(op.f('ix_task_history_task_id'), 'task_history', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_history_task_id'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_is_rolled_back'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_is_auto'), table_name='task_history')
    op.drop_table('task_history')
    op.drop_index(op.f('ix_extraction_item_extraction_id'), table_name='extraction_item')
    op.drop_table('extraction_item')
    op.drop_index(op.f('ix_alias_review_log_id'), table_name='alias_review')
    op.drop_table('alias_review')
    op.drop_index(op.f('ix_task_workspace_id'), table_name='task')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_due_date'), table_name='task')
    op.drop_index(op.f('ix_task_assignee_member_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_member_alias_workspace_id'), table_name='member_alias')
    op.drop_index(op.f('ix_member_alias_member_id'), table_name='member_alias')
    op.drop_index(op.f('ix_member_alias_alias_text'), table_name='member_alias')
    op.drop_table('member_alias')
    op.drop_table('meeting_audio')
    op.drop_index(op.f('ix_extraction_meeting_id'), table_name='extraction')
    op.drop_table('extraction')
    op.drop_index(op.f('ix_audio_segment_merged_start_ms'), table_name='audio_segment')
    op.drop_index(op.f('ix_audio_segment_meeting_id'), table_name='audio_segment')
    op.drop_table('audio_segment')
    op.drop_index(op.f('ix_alias_resolution_log_workspace_id'), table_name='alias_resolution_log')
    op.drop_index(op.f('ix_alias_resolution_log_alias_text'), table_name='alias_resolution_log')
    op.drop_table('alias_resolution_log')
    op.drop_index(op.f('ix_member_workspace_id'), table_name='member')
    op.drop_index(op.f('ix_member_notion_name'), table_name='member')
    op.drop_index(op.f('ix_member_discord_user_id'), table_name='member')
    op.drop_table('member')
    op.drop_index(op.f('ix_meeting_workspace_id'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_status'), table_name='meeting')
    op.drop_table('meeting')
    # ### end Alembic commands ###
