"""add task and approval link to extraction item

Revision ID: 472e12cbc1a0
Revises: 82b837cdba11
Create Date: 2026-09-16 13:31:38.285961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472e12cbc1a0'
down_revision: Union[str, Sequence[str], None] = '82b837cdba11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alias_resolution_log', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_alias_resolution_log_meeting_id_meeting'), 'meeting', ['meeting_id'], ['meeting_id'], ondelete='SET NULL')

    with op.batch_alter_table('extraction_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('approval_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_extraction_item_task_id_task'), 'task', ['task_id'], ['task_id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_extraction_item_approval_id_approval_request'), 'approval_request', ['approval_id'], ['approval_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraction_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_extraction_item_approval_id_approval_request'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_extraction_item_task_id_task'), type_='foreignkey')
        batch_op.drop_column('approval_id')
        batch_op.drop_column('task_id')

    with op.batch_alter_table('alias_resolution_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_alias_resolution_log_meeting_id_meeting'), type_='foreignkey')

    # ### end Alembic commands ###
