"""initial schema (postgresql)

SQLite 시절 마이그레이션 6개를 PostgreSQL 이관(#98)에 맞춰 하나로 합쳤다.
옛 마이그레이션은 SQLite 전용 테이블 복사 방식(recreate="always")을 써서 PostgreSQL에서
적용되지 않았다. 기존 SQLite 데이터는 옮기지 않으므로 현재 모델 기준으로 새로 만든다.

Revision ID: 4b7e13b98e39
Revises: 
Create Date: 2026-09-27 22:18:48.998285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7e13b98e39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('workspace',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('workspace_id', name=op.f('pk_workspace'))
    )
    op.create_table('integration',
    sa.Column('integration_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('provider_channel_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], name=op.f('fk_integration_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('integration_id', name=op.f('pk_integration')),
    sa.UniqueConstraint('workspace_id', 'provider', name='uq_workspace_provider')
    )
    op.create_index(op.f('ix_integration_workspace_id'), 'integration', ['workspace_id'], unique=False)
    op.create_table('meeting',
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('failed_stage', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], name=op.f('fk_meeting_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id', name=op.f('pk_meeting'))
    )
    op.create_index(op.f('ix_meeting_status'), 'meeting', ['status'], unique=False)
    op.create_index(op.f('ix_meeting_workspace_id'), 'meeting', ['workspace_id'], unique=False)
    op.create_table('member',
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('discord_user_id', sa.String(length=64), nullable=True),
    sa.Column('notion_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_member_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], name=op.f('fk_member_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id', name=op.f('pk_member')),
    sa.UniqueConstraint('workspace_id', 'discord_user_id', name='uq_workspace_discord_user')
    )
    op.create_index(op.f('ix_member_discord_user_id'), 'member', ['discord_user_id'], unique=False)
    op.create_index(op.f('ix_member_is_deleted'), 'member', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_member_notion_name'), 'member', ['notion_name'], unique=False)
    op.create_index(op.f('ix_member_user_id'), 'member', ['user_id'], unique=False)
    op.create_index(op.f('ix_member_workspace_id'), 'member', ['workspace_id'], unique=False)
    op.create_table('session',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_session_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_session'))
    )
    op.create_index(op.f('ix_session_session_token'), 'session', ['session_token'], unique=True)
    op.create_index(op.f('ix_session_user_id'), 'session', ['user_id'], unique=False)
    op.create_table('alias_resolution_log',
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('alias_text', sa.String(length=100), nullable=False),
    sa.Column('resolved_member_id', sa.String(length=36), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('meeting_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.meeting_id'], name=op.f('fk_alias_resolution_log_meeting_id_meeting'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_member_id'], ['member.member_id'], name=op.f('fk_alias_resolution_log_resolved_member_id_member'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], name=op.f('fk_alias_resolution_log_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_alias_resolution_log'))
    )
    op.create_index(op.f('ix_alias_resolution_log_alias_text'), 'alias_resolution_log', ['alias_text'], unique=False)
    op.create_index(op.f('ix_alias_resolution_log_workspace_id'), 'alias_resolution_log', ['workspace_id'], unique=False)
    op.create_table('audio_segment',
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=True),
    sa.Column('discord_user_id', sa.String(length=64), nullable=True),
    sa.Column('merged_start_ms', sa.Integer(), nullable=False),
    sa.Column('merged_end_ms', sa.Integer(), nullable=False),
    sa.Column('actual_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('track_file_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.meeting_id'], name=op.f('fk_audio_segment_meeting_id_meeting'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], name=op.f('fk_audio_segment_member_id_member'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('segment_id', name=op.f('pk_audio_segment'))
    )
    op.create_index(op.f('ix_audio_segment_meeting_id'), 'audio_segment', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_audio_segment_merged_start_ms'), 'audio_segment', ['merged_start_ms'], unique=False)
    op.create_table('extraction',
    sa.Column('extraction_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('transcript_path', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.meeting_id'], name=op.f('fk_extraction_meeting_id_meeting'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('extraction_id', name=op.f('pk_extraction'))
    )
    op.create_index(op.f('ix_extraction_meeting_id'), 'extraction', ['meeting_id'], unique=False)
    op.create_table('meeting_audio',
    sa.Column('audio_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('merged_file_path', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('track_count', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.meeting_id'], name=op.f('fk_meeting_audio_meeting_id_meeting'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audio_id', name=op.f('pk_meeting_audio')),
    sa.UniqueConstraint('meeting_id', name=op.f('uq_meeting_audio_meeting_id'))
    )
    op.create_table('member_alias',
    sa.Column('alias_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('alias_text', sa.String(length=100), nullable=False),
    sa.Column('alias_type', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], name=op.f('fk_member_alias_member_id_member'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], name=op.f('fk_member_alias_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alias_id', name=op.f('pk_member_alias')),
    sa.UniqueConstraint('workspace_id', 'member_id', 'alias_text', name='uq_alias_per_member')
    )
    op.create_index(op.f('ix_member_alias_alias_text'), 'member_alias', ['alias_text'], unique=False)
    op.create_index(op.f('ix_member_alias_member_id'), 'member_alias', ['member_id'], unique=False)
    op.create_index(op.f('ix_member_alias_workspace_id'), 'member_alias', ['workspace_id'], unique=False)
    op.create_table('task',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('assignee_member_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('blocker', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notion_page_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('notion_synced_version', sa.Integer(), nullable=True),
    sa.Column('notion_sync_status', sa.String(length=16), nullable=True),
    sa.Column('notion_create_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_member_id'], ['member.member_id'], name=op.f('fk_task_assignee_member_id_member'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.meeting_id'], name=op.f('fk_task_meeting_id_meeting'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], name=op.f('fk_task_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_task'))
    )
    op.create_index(op.f('ix_task_assignee_member_id'), 'task', ['assignee_member_id'], unique=False)
    op.create_index(op.f('ix_task_due_date'), 'task', ['due_date'], unique=False)
    op.create_index(op.f('ix_task_start_date'), 'task', ['start_date'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('ix_task_workspace_id'), 'task', ['workspace_id'], unique=False)
    op.create_table('alias_review',
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('corrected_member_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corrected_member_id'], ['member.member_id'], name=op.f('fk_alias_review_corrected_member_id_member'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['log_id'], ['alias_resolution_log.log_id'], name=op.f('fk_alias_review_log_id_alias_resolution_log'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['member.member_id'], name=op.f('fk_alias_review_reviewed_by_member')),
    sa.PrimaryKeyConstraint('review_id', name=op.f('pk_alias_review'))
    )
    op.create_index(op.f('ix_alias_review_log_id'), 'alias_review', ['log_id'], unique=False)
    op.create_table('approval_request',
    sa.Column('approval_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('related_task_id', sa.String(length=36), nullable=True),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['related_task_id'], ['task.task_id'], name=op.f('fk_approval_request_related_task_id_task'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['member.member_id'], name=op.f('fk_approval_request_requested_by_member'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['member.member_id'], name=op.f('fk_approval_request_resolved_by_member'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], name=op.f('fk_approval_request_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('approval_id', name=op.f('pk_approval_request'))
    )
    op.create_index(op.f('ix_approval_request_related_task_id'), 'approval_request', ['related_task_id'], unique=False)
    op.create_index(op.f('ix_approval_request_status'), 'approval_request', ['status'], unique=False)
    op.create_index(op.f('ix_approval_request_workspace_id'), 'approval_request', ['workspace_id'], unique=False)
    op.create_table('notion_sync_job',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('task_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], name=op.f('fk_notion_sync_job_task_id_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', name=op.f('pk_notion_sync_job')),
    sa.UniqueConstraint('task_id', 'task_version', name='uq_notion_sync_job_task_version')
    )
    op.create_index(op.f('ix_notion_sync_job_next_attempt_at'), 'notion_sync_job', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_notion_sync_job_status'), 'notion_sync_job', ['status'], unique=False)
    op.create_index(op.f('ix_notion_sync_job_task_id'), 'notion_sync_job', ['task_id'], unique=False)
    op.create_table('task_history',
    sa.Column('history_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('changed_field', sa.String(length=20), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('change_source', sa.String(length=16), nullable=False),
    sa.Column('changed_by', sa.String(length=36), nullable=True),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('is_rolled_back', sa.Boolean(), nullable=False),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['member.member_id'], name=op.f('fk_task_history_changed_by_member'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], name=op.f('fk_task_history_task_id_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id', name=op.f('pk_task_history'))
    )
    op.create_index(op.f('ix_task_history_is_auto'), 'task_history', ['is_auto'], unique=False)
    op.create_index(op.f('ix_task_history_is_rolled_back'), 'task_history', ['is_rolled_back'], unique=False)
    op.create_index(op.f('ix_task_history_task_id'), 'task_history', ['task_id'], unique=False)
    op.create_table('extraction_item',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('extraction_id', sa.String(length=36), nullable=False),
    sa.Column('task_title', sa.String(length=300), nullable=False),
    sa.Column('task_confidence', sa.Float(), nullable=False),
    sa.Column('assignee_raw', sa.String(length=100), nullable=True),
    sa.Column('assignee_member_id', sa.String(length=36), nullable=True),
    sa.Column('assignee_confidence', sa.Float(), nullable=False),
    sa.Column('assignee_needs_check', sa.Boolean(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_raw', sa.String(length=100), nullable=True),
    sa.Column('due_confidence', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('gate', sa.String(length=10), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('evidence_speaker', sa.String(length=100), nullable=True),
    sa.Column('evidence_at_ms', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('approval_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approval_request.approval_id'], name=op.f('fk_extraction_item_approval_id_approval_request'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assignee_member_id'], ['member.member_id'], name=op.f('fk_extraction_item_assignee_member_id_member'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['extraction_id'], ['extraction.extraction_id'], name=op.f('fk_extraction_item_extraction_id_extraction'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], name=op.f('fk_extraction_item_task_id_task'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_extraction_item'))
    )
    op.create_index(op.f('ix_extraction_item_extraction_id'), 'extraction_item', ['extraction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_item_extraction_id'), table_name='extraction_item')
    op.drop_table('extraction_item')
    op.drop_index(op.f('ix_task_history_task_id'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_is_rolled_back'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_is_auto'), table_name='task_history')
    op.drop_table('task_history')
    op.drop_index(op.f('ix_notion_sync_job_task_id'), table_name='notion_sync_job')
    op.drop_index(op.f('ix_notion_sync_job_status'), table_name='notion_sync_job')
    op.drop_index(op.f('ix_notion_sync_job_next_attempt_at'), table_name='notion_sync_job')
    op.drop_table('notion_sync_job')
    op.drop_index(op.f('ix_approval_request_workspace_id'), table_name='approval_request')
    op.drop_index(op.f('ix_approval_request_status'), table_name='approval_request')
    op.drop_index(op.f('ix_approval_request_related_task_id'), table_name='approval_request')
    op.drop_table('approval_request')
    op.drop_index(op.f('ix_alias_review_log_id'), table_name='alias_review')
    op.drop_table('alias_review')
    op.drop_index(op.f('ix_task_workspace_id'), table_name='task')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_start_date'), table_name='task')
    op.drop_index(op.f('ix_task_due_date'), table_name='task')
    op.drop_index(op.f('ix_task_assignee_member_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_member_alias_workspace_id'), table_name='member_alias')
    op.drop_index(op.f('ix_member_alias_member_id'), table_name='member_alias')
    op.drop_index(op.f('ix_member_alias_alias_text'), table_name='member_alias')
    op.drop_table('member_alias')
    op.drop_table('meeting_audio')
    op.drop_index(op.f('ix_extraction_meeting_id'), table_name='extraction')
    op.drop_table('extraction')
    op.drop_index(op.f('ix_audio_segment_merged_start_ms'), table_name='audio_segment')
    op.drop_index(op.f('ix_audio_segment_meeting_id'), table_name='audio_segment')
    op.drop_table('audio_segment')
    op.drop_index(op.f('ix_alias_resolution_log_workspace_id'), table_name='alias_resolution_log')
    op.drop_index(op.f('ix_alias_resolution_log_alias_text'), table_name='alias_resolution_log')
    op.drop_table('alias_resolution_log')
    op.drop_index(op.f('ix_session_user_id'), table_name='session')
    op.drop_index(op.f('ix_session_session_token'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_member_workspace_id'), table_name='member')
    op.drop_index(op.f('ix_member_user_id'), table_name='member')
    op.drop_index(op.f('ix_member_notion_name'), table_name='member')
    op.drop_index(op.f('ix_member_is_deleted'), table_name='member')
    op.drop_index(op.f('ix_member_discord_user_id'), table_name='member')
    op.drop_table('member')
    op.drop_index(op.f('ix_meeting_workspace_id'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_status'), table_name='meeting')
    op.drop_table('meeting')
    op.drop_index(op.f('ix_integration_workspace_id'), table_name='integration')
    op.drop_table('integration')
    op.drop_table('workspace')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
