"""Add Workspace model and relationships

Revision ID: 82b837cdba11
Revises: 051b67bf8358
Create Date: 2026-09-15 21:23:15.377558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b837cdba11'
down_revision: Union[str, Sequence[str], None] = '051b67bf8358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.add_column('alias_resolution_log', sa.Column('resolved_member_id', sa.String(length=36), nullable=True))
    op.drop_constraint(None, 'alias_resolution_log', type_='foreignkey')
    op.create_foreign_key(None, 'alias_resolution_log', 'meeting', ['meeting_id'], ['meeting_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'alias_resolution_log', 'workspace', ['workspace_id'], ['workspace_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'alias_resolution_log', 'member', ['resolved_member_id'], ['member_id'], ondelete='SET NULL')
    op.drop_column('alias_resolution_log', 'resolved_member')
    op.add_column('alias_review', sa.Column('corrected_member_id', sa.String(length=36), nullable=True))
    op.drop_constraint(None, 'alias_review', type_='foreignkey')
    op.create_foreign_key(None, 'alias_review', 'member', ['corrected_member_id'], ['member_id'], ondelete='SET NULL')
    op.drop_column('alias_review', 'corrected_member')
    op.create_foreign_key(None, 'approval_request', 'workspace', ['workspace_id'], ['workspace_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'meeting', 'workspace', ['workspace_id'], ['workspace_id'], ondelete='CASCADE')
    op.drop_column('meeting', 'audio_merged')
    op.drop_column('meeting', 'transcribed')
    op.drop_column('meeting', 'extracted')
    op.alter_column('member', 'discord_user_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_index(op.f('ix_member_discord_user_id'), table_name='member')
    op.create_index(op.f('ix_member_discord_user_id'), 'member', ['discord_user_id'], unique=False)
    op.create_unique_constraint('uq_workspace_discord_user', 'member', ['workspace_id', 'discord_user_id'])
    op.create_foreign_key(None, 'member', 'workspace', ['workspace_id'], ['workspace_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'member_alias', 'workspace', ['workspace_id'], ['workspace_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task', 'workspace', ['workspace_id'], ['workspace_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'member_alias', type_='foreignkey')
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.drop_constraint('uq_workspace_discord_user', 'member', type_='unique')
    op.drop_index(op.f('ix_member_discord_user_id'), table_name='member')
    op.create_index(op.f('ix_member_discord_user_id'), 'member', ['discord_user_id'], unique=1)
    op.alter_column('member', 'discord_user_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.add_column('meeting', sa.Column('extracted', sa.BOOLEAN(), nullable=False))
    op.add_column('meeting', sa.Column('transcribed', sa.BOOLEAN(), nullable=False))
    op.add_column('meeting', sa.Column('audio_merged', sa.BOOLEAN(), nullable=False))
    op.drop_constraint(None, 'meeting', type_='foreignkey')
    op.drop_constraint(None, 'approval_request', type_='foreignkey')
    op.add_column('alias_review', sa.Column('corrected_member', sa.VARCHAR(length=36), nullable=True))
    op.drop_constraint(None, 'alias_review', type_='foreignkey')
    op.create_foreign_key(None, 'alias_review', 'member', ['corrected_member'], ['member_id'], ondelete='SET NULL')
    op.drop_column('alias_review', 'corrected_member_id')
    op.add_column('alias_resolution_log', sa.Column('resolved_member', sa.VARCHAR(length=36), nullable=True))
    op.drop_constraint(None, 'alias_resolution_log', type_='foreignkey')
    op.drop_constraint(None, 'alias_resolution_log', type_='foreignkey')
    op.drop_constraint(None, 'alias_resolution_log', type_='foreignkey')
    op.create_foreign_key(None, 'alias_resolution_log', 'member', ['resolved_member'], ['member_id'], ondelete='SET NULL')
    op.drop_column('alias_resolution_log', 'resolved_member_id')
    op.drop_table('workspace')
    # ### end Alembic commands ###
