"""feat(db): User, Workspace 연동 및 프론트엔드 API 대응 스키마 추가

Revision ID: c643735a770a
Revises: 472e12cbc1a0
Create Date: 2026-09-19 17:53:53.573016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c643735a770a'
down_revision: Union[str, Sequence[str], None] = '472e12cbc1a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('integration',
    sa.Column('integration_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('provider_channel_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], name=op.f('fk_integration_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('integration_id', name=op.f('pk_integration')),
    sa.UniqueConstraint('workspace_id', 'provider', name='uq_workspace_provider')
    )
    with op.batch_alter_table('integration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('session',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_session_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_session'))
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_session_token'), ['session_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_session_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('alias_resolution_log', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_alias_resolution_log_resolved_member_id_member'), 'member', ['resolved_member_id'], ['member_id'], ondelete='SET NULL')

    with op.batch_alter_table('alias_review', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_alias_review_corrected_member_id_member'), 'member', ['corrected_member_id'], ['member_id'], ondelete='SET NULL')

    with op.batch_alter_table('extraction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_member_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_member_user_id_user'), 'user', ['user_id'], ['user_id'], ondelete='SET NULL')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_task_start_date'), ['start_date'], unique=False)

    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_completed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.drop_column('onboarding_completed')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_start_date'))
        batch_op.drop_column('start_date')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_member_user_id_user'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_member_user_id'))
        batch_op.drop_index(batch_op.f('ix_member_is_deleted'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('extraction', schema=None) as batch_op:
        batch_op.drop_column('summary')

    with op.batch_alter_table('alias_review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_alias_review_corrected_member_id_member'), type_='foreignkey')

    with op.batch_alter_table('alias_resolution_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_alias_resolution_log_resolved_member_id_member'), type_='foreignkey')

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_session_session_token'))

    op.drop_table('session')
    with op.batch_alter_table('integration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_workspace_id'))

    op.drop_table('integration')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
