"""add extraction item judge fields

AI의 Terra 2단계 판단 결과(action, category, status)와 PM에게 보여 줄 설명(doc_text)을
추출 항목에 기록한다(#102). 기존 row는 모두 새 task 항목이므로 action은 create로 채운다.

Revision ID: d8ed8221833e
Revises: 310f56922de3
Create Date: 2026-09-28 04:50:23.612927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ed8221833e'
down_revision: Union[str, Sequence[str], None] = '310f56922de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_item', sa.Column('action', sa.String(length=10), server_default='create', nullable=False))
    op.add_column('extraction_item', sa.Column('category', sa.String(length=16), nullable=True))
    op.add_column('extraction_item', sa.Column('status', sa.String(length=16), nullable=True))
    op.add_column('extraction_item', sa.Column('doc_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_item', 'doc_text')
    op.drop_column('extraction_item', 'status')
    op.drop_column('extraction_item', 'category')
    op.drop_column('extraction_item', 'action')
    # ### end Alembic commands ###
